on:
  push:
    branches:
      - main
      - prod-preview
  pull_request:
    branches:
      - main
      - prod-preview
    types:
      - opened
      - synchronize

concurrency:
  group: Release
  cancel-in-progress: false

jobs:
  check:
    if: always()
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs)}}
