on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: Release
  cancel-in-progress: false

jobs:
  test-check:
    uses: ./.github/workflows/tests.yml
  lint-check:
    uses: ./.github/workflows/lint.yml

  check:
    needs:
      - test-check
      - lint-check
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs)}}
