on:
  workflow_run:
    workflows: ['test', 'lint']
    branches:
      - main
      - prod-preview
    types:
      - completed

jobs:
  check:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: re-actors/alls-green@release/v1
        id: all-green
        with:
          jobs: ${{ toJSON(needs)}}
